const images = {
  chbox_selected: require('../../images/chbox_selected_signin_six.png'),
  drawerBG: require('../../images/drawerBG.png'),

  BreadAndPastries: require('../../images/BreadAndPastries.png'),
  Dairy: require('../../images/Dairy.png'),
  Fish: require('../../images/Fish.png'),
  Fruit: require('../../images/Fruit.png'),
  Meat: require('../../images/Meat.png'),
  Vagitable: require('../../images/Vagitable.png'),

  backBlackArrow: require('../../images/backBlackArrow.png'),
  FbIcon: require('../../images/fbicon.png'),
  TWIcon: require('../../images/ic_logo_twitter_signin_ten.png'),

  backArrow: require('../../images/backArrow.png'),
  backBlackArrow: require('../../images/backBlackArrow.png'),
  close_signin_15: require('../../images/close_signin_15.png'),
  back_signin_14: require('../../images/backArrow.png'),


  chbox_selected_signin_seven: require('../../images/chbox_selected_signin_seven.png'),

  backArrowSignUpTen: require('../../images/backArrowGrey.png'),
  backArrowSignUpNine: require('../../images/ic_Left_arrow_black_su09.png'),

  cart: require('../../images/cart.png'),
  search: require('../../images/search.png'),
  facebook: require('../../images/facebook.png'),
  mail: require('../../images/mail.png'),
  wtfourteenbg: require('../../images/wtfourteenbg.png'),
  rightArrowGreen: require('../../images/right_arrow_green.png'),
  menuIcon: require('../../images/ic_menu_white.png'),

  music: require('../../images/music.png'),
  film: require('../../images/film.png'),
  book: require('../../images/book.png'),
  game: require('../../images/game.png'),
  food: require('../../images/food.png'),
  sport: require('../../images/sport.png'),
  fashion: require('../../images/fashion.png'),
  draw: require('../../images/draw.png'),
  travel: require('../../images/travel.png'),
  eclipse: require('../../images/eclipse.png'),

  bgtwentyseven: require('../../images/bgtwentyseven.png'),
  dots: require('../../images/activess.png'),
  ic_check_box: require('../../images/ic_check_box.png'),
  ic_uncheck: require('../../images/ic_uncheck.png'),
  timer: require('../../images/timer.png'),
  likes: require('../../images/likes.png'),
  comments: require('../../images/comments.png'),
  location: require('../../images/location.png'),
  roundedcross: require('../../images/roundedcross.png'),

  //halak
  menuAlert: require('../../images/ic_menu_alert.png'),
  cameraIcon: require('../../images/ic_camera.png'),
  userGroup: require('../../images/ic_user.png'),
  searchGreyIcon: require('../../images/ic_search_grey.png'),
  voiceRecordingIcon: require('../../images/voice.png'),
  heartWhiteIcon: require('../../images/ic_heart_white.png'),
  mapPinIcon: require('../../images/ic_map_pin.png'),
  commentWhiteIcon: require('../../images/ic_comment_white.png'),
  moreWhiteIcon: require('../../images/ic_more_white.png'),
  cloude: require('../../images/cloude.png'),
  nearByIcon: require('../../images/ic_nearby_inactive.png'),
  messageIcon: require('../../images/ic_message.png'),
  discoveryIcon: require('../../images/ic_discovery.png'),
  favouriteIcon: require('../../images/ic_favourite.png'),
  profileIcon: require('../../images/ic_profile.png'),
  nearByActiveIcon: require('../../images/ic_nearby.png'),
  messageActiveIcon: require('../../images/ic_message_active.png'),
  discoveryActiveIcon: require('../../images/ic_discovery_active.png'),
  favouriteActiveIcon: require('../../images/ic_favourite_active.png'),
  profileActiveIcon: require('../../images/ic_profile_active.png'),
  watchIcon: require('../../images/watch.png'),
  mapPinWhite: require('../../images/ic_map_pin.png'),
  heartWhiteEmpty: require('../../images/white_empty_heart.png'),

  gradientTitleBarBG: require('../../images/gradient_bg.png'),
  albumIcon: require('../../images/ic_album.png'),
  createMessage: require('../../images/createMessage.png'),
  chatIcon: require('../../images/chatIcon.png'),
  videoIcon: require('../../images/videoIcon.png'),
  leftChatIndicator: require('../../images/leftChatIndicator.png'),
  rightChatIndicator: require('../../images/rightChatIndicator.png'),
  emoji: require('../../images/emoji.png'),

  cart_icon: require('../../images/cart_icon.png'),
  activeHome: require('../../images/activeHome.png'),
  activeCategory: require('../../images/activeCategory.png'),
  activeGift: require('../../images/activeGift.png'),
  normalHome: require('../../images/normalHome.png'),
  normalCategory: require('../../images/normalCategory.png'),
  normalGift: require('../../images/normalGift.png'),
  heavymetal:require('../../images/heavymetal.png'),
  country:require('../../images/country.png'),
  cartIconWhite: require('../../images/ic_cart.png'),
  sliderIcon: require('../../images/sliderIcon.png'),
  musicIcon: require('../../images/ic_music.png'),
  libraryIcon: require('../../images/ic_library.png'),
  radioIcon: require('../../images/ic_radio.png'),
  myLikesIcon: require('../../images/ic_my_likes.png'),
  search_fab: require('../../images/search_fab.png'),
  artical_fab: require('../../images/artical_fab.png'),
  message_fab: require('../../images/message_fab.png'),
  bell_fab: require('../../images/bell_fab.png'),
  favorite_fab: require('../../images/favorite_fab.png'),
  friends_fab: require('../../images/friends_fab.png'),
  logoutIcon: require('../../images/ic_logout.png'),

  addUserIcon: require('../../images/addUserIcon.png'),
  whiteTriangleIcon: require('../../images/whiteTriangleIcon.png'),
  messageBlueIcon: require('../../images/messageBlueIcon.png'),
  slideUpArrowIcon: require('../../images/ic_slide_up_arrow.png'),

  starFilled1: require('../../images/starFilled1.png'),
  starEmpty1: require('../../images/starEmpty1.png'),
  starHalf1: require('../../images/starHalf1.png'),

  //for Demo
  searchbg: require('../../images/searchbg.png'),

  //Premangi
  blueCameraIcon: require('../../images/blueCameraIcon.png'),
  setting: require('../../images/ic_setting.png'),
  phone: require('../../images/ic_phone.png'),
  video: require('../../images/ic_video.png'),
  google: require('../../images/ic_google.png'),
  addUserGray: require('../../images/ic_add_user_gray.png'),
  settingBlack: require('../../images/ic_setting_black.png'),
  googleWhite: require('../../images/ic_google_white.png'),

  //Viral
  livingRoom: require('../../images/ic_living_room.png'),
  diningRoom: require('../../images/ic_dining_room.png'),
  bookCase: require('../../images/ic_bookcase.png'),
  bedRoom: require('../../images/ic_bedroom.png'),
  tvStand: require('../../images/ic_tv_stand.png'),
  bathRoom: require('../../images/ic_bathroom.png'),


  livingRoomBlue: require('../../images/livingroom_blue.png'),
  diningRoomBlue: require('../../images/diningroom_blue.png'),
  bookCaseBlue: require('../../images/bookcase_blue.png'),
  bedRoomBlue: require('../../images/bedroom_blue.png'),
  tvStandBlue: require('../../images/tv_stands_blue.png'),
  bathRoomBlue: require('../../images/bathroom_blue.png'),

  bellnoti: require('../../images/bellnoti.png'),

  bgtwentyseven: require('../../images/bgtwentyseven.png'),

  mnavigation:require('../../images/mnavigation.png'),
  msignup:require('../../images/msignup.png'),
  msignin:require('../../images/msignin.png'),
  msocial:require('../../images/msocial.png'),
  muser:require('../../images/muser.png'),
  mwalkthrough:require('../../images/mwalkthrough.png'),

    admob: require('../../images/ic_ad_mob.png'),
}

export default images
